name: ci-cd
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install package
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest tests/ --cov=py_pkgs_tutorial --cov-report=xml
  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install package
        run: poetry install
      - name: Use Python Semantic Release to prepare release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            poetry run semantic-release publish